### ISSUE TITLE
Why is my maths bold in Markdown PDF?

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#100]
If I put this line in as LaTeX:

```
Here is some maths: \( x = \frac{b^2 - \sqrt{4 a c}}{2 a} \)
```

The output looks like this in HTML:

![Screenshot from 2021-09-17 11:58:37](https://user-images.githubusercontent.com/5698564/133771892-808d84c0-e7b7-4936-96a8-8200225a8731.png)

and like this in PDF:

![Screenshot from 2021-09-17 11:58:53](https://user-images.githubusercontent.com/5698564/133771925-e89968f2-c346-4f60-9799-c18953361bbe.png)

If I put the same code in a Markdown file, the output looks like this is HTML (which, to my eye, is indistinguishable):

![Screenshot from 2021-09-17 11:59:36](https://user-images.githubusercontent.com/5698564/133772016-62c74c96-da59-47e9-9f6f-b84cd0f1df7a.png)

but like this in PDF:

![Screenshot from 2021-09-17 11:59:55](https://user-images.githubusercontent.com/5698564/133772050-d62e300d-aaa1-4a45-84cf-3820ba68f625.png)

Perhaps it is a choice that has been made to make the maths bold, but I still mention it because if a design decision has been taken that maths should be bold (why?) then why not also in HTML? And pdflatex has made a different choice. Or perhaps it's a bug. At most reasonable zoom levels on my screen the bold makes it less readable.  

Out of curiosity, I did 

```
Here's an \(A\) and an \(\bm{A}\).
```

and got this in HTML 

![Screenshot from 2021-09-17 12:08:05](https://user-images.githubusercontent.com/5698564/133772968-07a5d143-f452-440e-a047-59220c645142.png)

and this in PDF

![Screenshot from 2021-09-17 12:08:28](https://user-images.githubusercontent.com/5698564/133773035-d0f2ef52-edbc-49f9-9ded-17d4395588c6.png)

I think the links on the bold A are a bit thicker (below at 1000% zoom), so it doesn't seem to be as simple as the maths being made bold.

![Screenshot from 2021-09-17 12:11:43](https://user-images.githubusercontent.com/5698564/133773406-0bbfa051-5f06-497d-a2c5-9b7e6366ca21.png)

**Comment by pkra** [comment]
Random bystander guess: 

a) it prints fine and varies with PDF viewer
b) MathJax v2 is used 
c) MathJax's v2 SVG output uses a non-zero `blacker` setting

**Comment by prowlett** [comment]
Oh yes, thanks @pkra, I should have said what viewer I'm using. 

I'm using Ubuntu. The screenshots in the original post are in Firefox 92.0. 

Here is a side-by-side in Firefox 92.0 at the same zoom (Markdown left, LaTeX right):

![Screenshot from 2021-09-17 13:46:04](https://user-images.githubusercontent.com/5698564/133784790-e8e501cb-c93f-421e-ba9e-3300b8b4e2d2.png)

Here's the same two files in Evince 40.4 at the same zoom (Markdown left, LaTeX right):

![Screenshot from 2021-09-17 13:48:42](https://user-images.githubusercontent.com/5698564/133784984-2703fd27-5678-4840-a33d-599c55e9a382.png)

I find this one much more readable, but still the maths is bolder than in the LaTeX. 

And here again, this time in Chromium 93.0.4577.82 at the same zoom (Markdown left, LaTeX right):

![Screenshot from 2021-09-17 15:49:05](https://user-images.githubusercontent.com/5698564/133803216-65bc6115-ebb9-48f8-abb6-9ab6875cfd3f.png)

I haven't tried printing it - I can do, if it would help. Let me know.

Re. @pkra's b) and c), I don't develop `makecourse` and don't understand how the Markdown files are turned into PDF, but I can see the webpage version is using MathJax 3.2.0.

**Comment by pkra** [comment]
> Re. @pkra's b) and c), I don't develop makecourse and don't understand how the Markdown files are turned into PDF, but I can see the webpage version is using MathJax 3.2.0.

Right. I wrote my comment more for @christianp. I've seen this in the past in my own projects. I don't use or know  coursebuilder.

**Comment by georgestagg** [comment]
@prowlett Could you please try updating to the latest `makecourse` commit and then add the below line to `config.yml`? This switches MathJax to use the `chtml` output format rather than the `svg` output currently in use, and it would be good to know if it makes a difference on your machine.

```mathjax_url: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'```

If it helps, probably I can just switch the default until I know more about what's going on.

**Comment by prowlett** [comment]
@georgestagg That is certainly different, but not better. The output from 

```
Here is some maths: \( x = \frac{b^2 - \sqrt{4 a c}}{2 a} \)

Here's an \(A\) and an \(\bm{A}\).
```

now looks like this:

![Screenshot from 2021-09-20 14:35:44](https://user-images.githubusercontent.com/5698564/134011693-58d1616c-d27b-45a4-940d-80fcd7e5a152.png)

**Comment by georgestagg** [comment]
Thanks, I'll keep investigating.

**Comment by prowlett** [comment]
Should perhaps qualify "better" - the text is clearer, but the letters are not italic, there's a break in the square root sign and I can't tell the `\bm{A}` from the `A`.

**Comment by christianp** [comment]
The new theme uses MathJax 3, and the PDF output looks good:
![image](https://github.com/chirun-ncl/chirun/assets/19513/f591d2f0-ee40-411d-8ffd-4d635da1ce6c)
