### ISSUE TITLE
The plastex compiler does not seem to support labelling subequations properly

### ISSUE THREAD

**Issue by georgestagg** [chirun-ncl/chirun#106]

**Comment by christianp** [comment]
@georgestagg can you give a minimal example of this, if you can remember what it's about?

**Comment by georgestagg** [comment]
Consider the following source document,

```
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\section{A section}
\begin{subequations}\label{lorenz}
	\begin{align}
		\dot x &= \sigma(y-x)   \label{l1} \\
		\dot y &= x(\rho-z) - y \label{l2} \\
		\dot z &= xy - \beta z  \label{l3}
	\end{align}
\end{subequations}
\section{Another section}
Labelling \ref{lorenz}, \ref{l2}.
\end{document}

```

With `pdflatex` the output looks like this:
![Screenshot 2023-10-11 at 08 45 47](https://github.com/chirun-ncl/chirun/assets/982548/c1146e84-1ea0-4a5d-8181-d00a7b0dd85e)

With Chirun the output looks like this:
![Screenshot 2023-10-11 at 08 45 51](https://github.com/chirun-ncl/chirun/assets/982548/332540b8-fb74-4302-a531-5724347a3cb8)

It's likely that `subequation` is not implemented in plastex's `amsmath`.

**Comment by christianp** [comment]
@georgestagg thanks!
It does look like plasTeX would have to implement this.

**Comment by christianp** [comment]
Now implemented.
