### ISSUE TITLE
LaTeX \footnote presentation in web mode - size

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#108]
We had an issue in class today where there were footnotes on a coursework brief that included numbered questions. A student thought the numbered footnotes were a new set of questions. One issue is the footnote text isn't presented very differently to normal text. In pdflatex this would be smaller (with accessibility worries, of course) and presented slightly different (it looks to me that the numbers are superscript and no dots), which makes it look less like the other list. Anyway, to my eye the footnote list doesn't look like another numbered list.

```
\documentclass{article}

\begin{document}

~\vspace{14cm} % to make the PDF screenshot less tall

Here\footnote{On this page.} is some text\footnote{You know, writing words and so forth.} with a footnote.
\begin{enumerate}
    \item Presented the same size.
    \item Which could be confusing.
    \item For some readers.
\end{enumerate}

\end{document}
```

HTML version:

![Screenshot from 2021-11-30 17:01:24](https://user-images.githubusercontent.com/5698564/144093195-a06de54d-e7c6-46f2-aa3a-97955d3da2d0.png)

PDF version:

![Screenshot from 2021-11-30 17:02:17](https://user-images.githubusercontent.com/5698564/144093218-472b15ea-7d95-4d4a-a97f-fbdf2cad474e.png)

**Comment by christianp** [comment]
Intriguingly, the `::marker` CSS selector, for the list item marker, only allows a few properties. `vertical-align` isn't one of them, so I don't think I can make the number appear in superscript position while using the built-in list markers. 

But it would make sense to link back up to the place the footnote is referred to, so maybe we don't want to use built-in markers anyway.

**Comment by prowlett** [comment]
I think the 'Notes' header is very clear, however this would be a very different implementation to the LaTeX. However, the PDF has several advantages, including that the number is superscript like the footnote indicator in the text, and it is positioned at the bottom of the page consistently. Since neither work in the HTML, I'd say the addition of a 'Notes' header would be a reasonable compromise.
