### ISSUE TITLE
Option clash for package hyperref

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#120]
In LaTeX I set `\usepackage[hidelinks]{hyperref}` but it turned out the `chirun` package already includes `\usepackage{hyperref}` so I got `Option clash for package hyperref. \usepackage`. The fix is to have `\usepackage[hidelinks]{hyperref}` first before `\usepackage{chirun}`.

I don't know if there is a place in the documentation for known issues and workarounds where this would go.

**Comment by georgestagg** [comment]
Thanks, I've added a note to the documentation about this at https://chirun.readthedocs.io/en/latest/reference/chirun_latex.html#interaction-with-the-hyperref-package

I saw that the Beamer document class handles this in a quite nice way, where some package options can be passed through `beamer`.

I've implemented the same thing in eff2a7d366e3811abeab85aed6e8b40e0d81e16f. Loading `hyperref` with your options first should still work, but if you prefer you should be able to skip loading `hyperref` entirely now, instead passing options via `chirun`

```
\usepackage[hyperref={hidelinks}]{chirun}
```
