### ISSUE TITLE
chirun package (via a4wide) overrides page margins

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#121]
In LaTeX, I couldn't set the page margins using `geometry`. Investigating, I find this is because `chirun.sty` now includes `\usepackage{a4wide}` (if the document isn't beamer slides). 

The fix is to `\usepackage{chirun}` before `\usepackage[margin=??cm]{geometry}`.

I don't know if there is a place in the documentation for known issues and workarounds where this would go.

**Comment by georgestagg** [comment]
`a4wide` has now been removed from the `chirun` LaTeX package.
