### ISSUE TITLE
\ifplastex doesn't exist any more

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#124]
It seems #70acee5 removed `\newif\ifplastex\plastexfalse`.

I have a few hacks here and there which use `\ifplastex`. For example, it's mentioned in #48, #59 and #84. 

Anyway, I just upgraded `chirun` and now my notes won't compile. I added `\newif\ifplastex\plastexfalse` to the preamble of two files (one file is the one that caused issue #84 and the other is where I want something to appear on the webpage but not in the PDF that I'll print and hand out to students in class) and now it compiles fine.

I guess you were using `\ifplastex` for something but now aren't? But having it defined has been useful in the past for workarounds, and I'm sure I have files in other sets of notes that will need me to manually define it in each file where it's used once I try to compile those notes.

**Comment by georgestagg** [comment]
Apologies, I was a little overzealous removing some code. I can see that it is useful and it is now be back in the latest commit.

I think you will need to remove the extra `\newif` line you added to your preamble, the double `\newif` will probably cause a LaTeX error.

One day I will have unit tests to catch this kind of thing...

**Comment by prowlett** [comment]
Thank you! For some reason, pdflatex doesn't complain about a second `\newif` using the same name. For example, the following code runs fine, even though that seems (a) morally wrong; (b) inconsistent with other ways in which LaTeX works. Maybe because this construct is TeX not LaTeX? 🤷

```
\documentclass{article}
\newif\iflightning\lightningfalse
\newif\iflightning\lightningtrue
\begin{document}
    \iflightning It's alive! \else Nothing to see here. \fi
\end{document}
```

I removed my extra `\ifplastex` definitions anyway.
