### ISSUE TITLE
ImportError: cannot import name 'contextfilter' from 'jinja2'

### ISSUE THREAD

**Issue by rjsanchezgarcia** [chirun-ncl/chirun#129]
I've just install chirun but I get this ImportError, any help much appreciated. This post might be related https://github.com/d2l-ai/d2l-book/issues/46

**Comment by rjsanchezgarcia** [comment]
Full output
> chirun
Traceback (most recent call last):
  File "/Users/username/opt/anaconda3/envs/chirun/bin/chirun", line 16, in <module>
    from chirun.item import load_item
  File "/Users/username/opt/anaconda3/envs/chirun/lib/python3.10/site-packages/chirun/item.py", line 7, in <module>
    from .filter import HTMLFilter
  File "/Users/username/opt/anaconda3/envs/chirun/lib/python3.10/site-packages/chirun/filter.py", line 9, in <module>
    from .render import Renderer
  File "/Users/username/opt/anaconda3/envs/chirun/lib/python3.10/site-packages/chirun/render.py", line 6, in <module>
    from jinja2 import Environment, FileSystemLoader, select_autoescape, contextfilter, TemplateNotFound
ImportError: cannot import name 'contextfilter' from 'jinja2' (/Users/username/opt/anaconda3/envs/chirun/lib/python3.10/site-packages/jinja2/__init__.py)

**Comment by rjsanchezgarcia** [comment]
I think this is why https://jinja.palletsprojects.com/en/3.0.x/api/

jinja2.contextfilter(f)

    Pass the context as the first argument to the decorated function.

    Deprecated since version 3.0: Will be removed in Jinja 3.1. Use [pass_context()](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.pass_context) instead.

    Parameters

        f (jinja2.filters.F) –
    Return type

        jinja2.filters.F

**Comment by georgestagg** [comment]
Thanks. I'm aware of the problem but haven't yet had a chance to made the change to the code. For the moment you should be able to request install of `Jinja2<=3.0.0` using pip to get up and running until an update has been pushed to Chirun.

**Comment by rjsanchezgarcia** [comment]
Great, thank you George, works a treat.
