### ISSUE TITLE
distutils is deprecated and slated for removal in Python 3.12

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#133]
I upgraded my computer to Ubuntu 22.04 with Python 3.10.4 and upgraded chirun. I now get a `DeprecationWarning` when I run chirun, so I'm flagging it as a future issue:

```
/home/.../chirun_env/bin/chirun:13: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.dir_util import copy_tree
```

**Comment by christianp** [comment]
Thanks for reporting this. I think it can just be replaced with `shutil.copytree`.
