### ISSUE TITLE
MarkupResemblesLocatorWarning

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#134]
I upgraded my computer to Ubuntu 22.04 with Python 3.10.4, upgraded chirun, then cloned and compiled the sample course. This is the output.

I think the `DeprecationWarning` is a chirun future issue and so I've [raised it there](https://github.com/chirun-ncl/chirun/issues/133), but I think the `MarkupResemblesLocatorWarning`s are issues with the sample course content.

```
/home/.../chirun_env/bin/chirun:13: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.dir_util import copy_tree
Running chirun for directory /home/.../sample_course
/home/.../chirun_env/lib/python3.10/site-packages/bs4/__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(
/home/.../chirun_env/lib/python3.10/site-packages/bs4/__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(
Output written to /home/.../sample_course/build
```

**Comment by christianp** [comment]
Thanks! It was the forward slash in `intro.tex`, which is completely reasonable to be there.

I've made a change to the filter code so it avoids triggering this warning.
