### ISSUE TITLE
Global Flags Error

### ISSUE THREAD

**Issue by RailEngMaths** [chirun-ncl/chirun#154]
I have followed the [installation instructions](https://chirun.readthedocs.io/en/latest/getting_started/cli/install.html) for MacOS and am using the Conda environment. I used the sample course to test if all was good, but ...

![image](https://github.com/chirun-ncl/chirun/assets/109075537/1d23913a-8d4d-43bc-8eb5-1edcd071b6e3)

I am getting the error: global flags not at the start of the expression at position 32.

I don't know what this means, please could you advise?

Many thanks,
Alex

**Comment by christianp** [comment]
It's not clear where that error is coming from. It's a Python error; what version of Python are you using?
Do you get any more information if you run `chirun -vv`?

**Comment by christianp** [comment]
By looking at other references to this error message, I think this is a breaking change in python 3.11. I'll see if I can reproduce it.

**Comment by RailEngMaths** [comment]
Hi Chris. Thank you. 

The version of Python is 3.11.4. I ran Chirun -vv and this was the final output:

![image](https://github.com/chirun-ncl/chirun/assets/109075537/f0157fe1-4f85-4dbc-871c-5e82b8589581)

**Comment by christianp** [comment]
Great, thanks!

**Comment by christianp** [comment]
@RailEngMaths I think I've found the cause of the problem and fixed it. Can you have another go and tell me if it works OK?

I've just merged my recent developments from the `dev` branch into `master`, so when you do `git pull` there will be lots more commits than just the one fixing this.
