### ISSUE TITLE
Accessible version should contain the same information as the default

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#17]
For example, the course homepage lists:
- course title
- author
- year
- introductory paragraph
- boxes for course materials
- introduction file text
- copyright notice
- your credit
- date site was last generated
- back to top
- theme switcher

The accessible version lists:
- course title
- course materials (that the introductory paragraph appears multiple times under each `h3` here is raised as #16)
- introduction file text
- back to top
- theme switcher

The accessible version is therefore missing a bunch of metadata:
- author
- year
- copyright notice
- your credit
- date site was last generated

**Comment by georgestagg** [comment]
The old "accessible" theme has now been deleted. The default theme can now do the kinds of things it was originally used for via customisation.
