### ISSUE TITLE
Runnable code output takes up considerable vertical height

### ISSUE THREAD

**Issue by chrismgraham** [chirun-ncl/chirun#175]
In the slides view, the output from runnable code extends vertically to fit its content, which makes it difficult to manage content so that it fits within the vertical height. 

The output could float to the right of the input, or be scrollable with a max-height. Perhaps a combination of both might be best: sometimes I do want to demonstrate error messages which can be very lengthy, so I think a backstop of a max-height is helpful.

**Comment by christianp** [comment]
Does this look OK? There's enough space for one line of text above and below.

![image](https://github.com/chirun-ncl/chirun/assets/19513/c5b6c144-8d93-4bda-afc6-b7897cc537fc)

**Comment by chrismgraham** [comment]
That looks great!
