### ISSUE TITLE
Slide sections overflow main, cutting off content 

### ISSUE THREAD

**Issue by chrismgraham** [chirun-ncl/chirun#177]
I think that in the slides view, sections have some padding which is added to the 100vw causing it to overflow main (which uses overflow: hidden). This causes the right side of the slides to be cut off (or at least give the appearance of no right padding).

<img style="border: 1px solid black;" width="900" alt="Screenshot 2023-09-20 at 16 25 25" src="https://github.com/chirun-ncl/chirun/assets/15893967/f80c7839-225e-442e-b946-6def776ec554">

**Comment by christianp** [comment]
I think I fixed this in 85143009888b3fbeab06f38f6a8915bc18fda519. Can you check?

**Comment by chrismgraham** [comment]
Yes, that's sorted it
