### ISSUE TITLE
Pick a documentation site and refer to it consistently

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#179]
The GitHub repo says

> The Chirun documentation, including information about the Chirun Public Content Builder and Chirun LTI Provider can be found at, 
> https://chirun.readthedocs.io/en/latest/

Whereas [chirun.org.uk](https://chirun.org.uk) points to 

> **Chirun documentation**
> [chirun.org.uk/docs](https://chirun.org.uk/docs)

These don't appear to be exact mirrors (for example, the former has four subheadings under 'Chirun Python Package', whereas the latter has three subheadings under 'The Chirun Python package'. 

So which is it? And point consistently to it, for example if you're not using readthedocs.io any more maybe redirect it or blank it apart from a message saying here's where to find the current version.

**Comment by christianp** [comment]
Thank you for pointing this out. Please understand that I'm still in the middle of updating everything so there are places I haven't got to yet.

**Comment by prowlett** [comment]
Definitely, understood. I'm trying to take the approach of pointing things out as I see them, trying to be helpful and certainly not intending to have a go at you!
