### ISSUE TITLE
itemize is numbered

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#180]
In a LaTeX `chapter`, this code:

```
\documentclass{article}
\begin{document}
    \begin{itemize}
        \item Hello.
        \item Goodbye.
    \end{itemize}
\end{document}
```

produces this in PDF:

![image](https://github.com/chirun-ncl/chirun/assets/5698564/26bc22fe-92ad-48bb-b761-6b8b8672ff42)

but this in HTML:

![image](https://github.com/chirun-ncl/chirun/assets/5698564/4237daab-46ca-4312-b0a6-bf99ebb56a0f)

In Beamer, this code:

```
\documentclass{beamer}
\begin{document}
    \begin{frame}{Start}
        \begin{itemize}
            \item Hello.
            \item Goodbye.
        \end{itemize}
    \end{frame}
\end{document}
```

produces this in PDF

![image](https://github.com/chirun-ncl/chirun/assets/5698564/f27e2c56-2552-4321-8718-dee5f0e81b37)

but this in HTML 

![image](https://github.com/chirun-ncl/chirun/assets/5698564/82372ea9-cc3d-4321-b219-80ff1960a564)

and this in the Slides HTML

![image](https://github.com/chirun-ncl/chirun/assets/5698564/1da041a7-e3b1-478a-bdca-74761f27047c)

**Comment by christianp** [comment]
I don't think we can unit test this because the method for list items that this issue was about was implemented in CSS, so you can't tell just from looking at the HTML what marker will be used.
