### ISSUE TITLE
A few style suggestions

### ISSUE THREAD

**Issue by chrismgraham** [chirun-ncl/chirun#188]
A few suggestions for style changes that I've added to custom.css but think might be appropriate for the main stylesheet. Feel free to ignore any that are just my personal likes!

- I have some slides with quotes from feedback last year that I use. Blockquotes are currently set to `calc(0.5* var(--readable-width))`, but it seems reasonable to have the default as full width
```
main > section blockquote {
      max-width: calc(1.0 * var(--readable-width));
}
```

- Maybe just personal preference, but I found the slides seem quite close to the left/right margins, particular when short paragraphs are used, the left aligned text feels very far to the left. 2rem feels better to me
```
body > main {
    padding: 0 2rem;
}
```

- In a markdown chapter/noteback now. Again, this might just be a personal preference, but I prefer a but more spacing in front of the headings, to split content sections a little bit more clearly. h1 is OK since it's at the top, but I've got the following, which seem to work well:
```
#item-content h2 {
  margin-top: calc(3*var(--spacing));
}

#item-content h3 {
  margin-top: calc(2*var(--spacing));
}
```

- For code display, my preference is for the code output blocks to be pressed up to the input box that's usually above it. I find that the following works reliably when changing font size etc. Obviously a standalone block you wouldn't want this, so I wonder if there's a case for having an output class that has negative margin and a standalone class that doesn't
```
.output-block{
  margin-top: -1em;
}
```

- And finally, I found that the code blocks didn't really stand out from the main text, particularly the output which I think uses the page background colour. So I'm in favour of something like
```
pre {
  border: 1px solid #CCC;
}
```

**Comment by christianp** [comment]
Can you give an example of what you mean about `.output-block`?

**Comment by chrismgraham** [comment]
Sure, so this code
```python
2/3
```
```output
0.6666666666666666
```
gives this output 
<img width="876" alt="Screenshot 2023-09-22 at 10 30 06" src="https://github.com/chirun-ncl/chirun/assets/15893967/68aec70a-7421-461b-a017-d2a03cc4555d">
and this with the proposed adjustment
<img width="877" alt="Screenshot 2023-09-22 at 10 30 24" src="https://github.com/chirun-ncl/chirun/assets/15893967/ffaf730b-b6db-441a-be7a-e5761362c122">

**Comment by chrismgraham** [comment]
Ah, Github rendered the source, but hopefully you can see what I mean
