### ISSUE TITLE
Numbas embed "Test Yourself" link uses the auto cursor style

### ISSUE THREAD

**Issue by chrismgraham** [chirun-ncl/chirun#192]
The link to expand a Numbas embed item uses the auto cursor style, rather than e.g. pointer

It's actually just a heading tag, so maybe it should also have a title?

**Comment by christianp** [comment]
What kind of title do you mean?

**Comment by chrismgraham** [comment]
The thing that you click on to expand and load the test is 
```
<h1 id="title">Test Yourself</h1>
```
(also has a ::before with a little arrow which is clickable)

**Comment by chrismgraham** [comment]
Ah, I think I see from your commit that it's actually the <summary> (parent of the h1) that you're clicking on
