### ISSUE TITLE
What is custom.css?

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#193]
In #188 @chrismgraham said 

> A few suggestions for style changes that I've added to custom.css but think might be appropriate for the main stylesheet.

What is `custom.css`? 

My guess was that this might be a file where I can add my own custom CSS code that would be additive with what is provided by chirun. I tried creating a file at `static/custom.css`. When I run `chirun`, it copies this file to `built/static/custom.css`, but as far as I can see this isn't referred to in the HTML files so I don't think it is being used for anything.

**Comment by chrismgraham** [comment]
Hi Peter, it is, but I think it's good to try not to use it (hence my suggestions for putting in the main stylesheet), so as to not deviate from the approved (accessible) styles. You can include in the config.yml (at the top) with
```
css: 
  - custom.css
```
and place it in the static folder

**Comment by prowlett** [comment]
Ah cool, thanks. At the moment I've got a copy of the current `styles.css` file with my fix proposed in #184 in it, and this would replace that more sensibly. But I agree in general this is nice to have but best to avoid using if possible.
