### ISSUE TITLE
A "build this?" flag for items in the config's structure

### ISSUE THREAD

**Issue by christianp** [chirun-ncl/chirun#197]
For things like homework solutions, it'd be nice to be able to prepare them in advance, but not include them in the output until they're supposed to be available.

**Comment by prowlett** [comment]
I would use this! I often have exercise solutions or a post-class version of the slides to replace the pre-class spoiler-free version, or indeed upcoming weeks that I have got ready but am not ready to release to students yet. I comment these out in `config.yml`, which is fairly straightforward via a keyboard shortcut but I guess a flag would be better.

**Comment by christianp** [comment]
There was already the property `is_hidden`, but it wasn't implemented properly in the command-line tool - I think the old LTI tool might have used it to control access to built pages.

I've changed the template of the structure pages so they don't show hidden items, and added a hash to the URLs of hidden items so they can't be guessed by students, while maintaining consistent URLs so you can link to them.
