### ISSUE TITLE
List features in the README

### ISSUE THREAD

**Issue by sieste** [chirun-ncl/chirun#2]
Hi, 
I just came here from the numbas newsletter that came through today to check out CourseBuilder. I read the README and followed a couple of links to the website and other repositories. Before giving this software a try I would like to know what the distinguishing features are, and why I would want to use coursebuilder rather than simply compiling my lecture notes with latex or pandoc. Would be great if you could clarify this somewhere where it's easy to find.
Cheers, Stefan

**Comment by georgestagg** [comment]
Chirun has much better documentation now at https://chirun.readthedocs.io/en/latest/index.html, which README links to.
