### ISSUE TITLE
Runnable code in slide view makes page slightly wider than screenwidth

### ISSUE THREAD

**Issue by wrushworth** [chirun-ncl/chirun#215]
A runnable code snippet in slide view makes that slide slightly larger than the screenwidth:

![image](https://github.com/chirun-ncl/chirun/assets/89534988/93ef31eb-0504-4813-a721-c9daea98d2fa)

The output box also has unlimited width, which makes the slide very wide relative to the screenwidth:

![image](https://github.com/chirun-ncl/chirun/assets/89534988/b5b8242c-1d8b-4d5f-8871-7af3d481ad7e)

**Comment by christianp** [comment]
Seems to only happen in Chrome. I thought css compatibility was supposed to not be a problem any more! 

I'll see if I can fix it.
