### ISSUE TITLE
amsthm/proof not showing text

### ISSUE THREAD

**Issue by IanHawke** [chirun-ncl/chirun#218]
With chirun 1.1.0 the document

```
\documentclass[a4paper]{report}
\usepackage{amsmath,amsthm,chirun}

\newtheorem{thm}{Theorem}

\begin{document}

\begin{thm}
  Hello world
\end{thm}
\begin{proof}
  Does this show?
\end{proof}

\end{document}
```

does not show the text in the proof in the HTML output. Tested as a local build on Mac and also with the web front end.

**Comment by IanHawke** [comment]
I can confirm that the problem didn't show up with version 1.0.

**Comment by christianp** [comment]
Thanks for reporting this! We had a real headache trying to work out how the template for `proof` environments should work: it seems that it behaves very differently if you define it with `\newenvironment` compared to having it defined by `amsthm`.
I think I've fixed it now so it should work both ways.
