### ISSUE TITLE
LaTeX HTML output: \ref in math mode doesn't pick up references to labels defined in text mode

### ISSUE THREAD

**Issue by christianp** [chirun-ncl/chirun#219]
In the HTML output of a LaTeX document, a `\ref` command in math mode will not recognise labels defined in text mode elsewhere in the document. 
I think that MathJax makes its own list of references, and plasTeX doesn't fill it with the text mode references. I need to find out if that's possible.

**Comment by pkra** [comment]
The "usual" author hack is to do `$\ref{mathmodelabel}$` when an HTML convertor leaves math mode untouched for MathJax. (I only know one convertor that does it "properly", i.e., resolve label/IDs but still leave good math mode TeX in the output for MathJax.)

**Comment by christianp** [comment]
Fixed by d2d371e67111336c223509a551944d7acff29352

**Comment by christianp** [comment]
I think the only way to unit test this is to check the dictionary of labels that MathJax should load.
