### ISSUE TITLE
pdf2svg missing function called

### ISSUE THREAD

**Issue by Alex-Corner** [chirun-ncl/chirun#231]
The commit 2c555d4 updated the renderer for pdf2svg, but removed the import for the function `Image` from `plasTeX.Images`. `Image` is still called on Line 32 of 2c555d4 and I think this is causing the error `NameError: name 'Image' is not defined` when loading .pdf files as graphics in Chirun builds.

**Comment by christianp** [comment]
Whoops, sorry! I'm on holiday today but I'll try and get it fixed ASAP.
We really do need some unit tests.
