### ISSUE TITLE
Markdown image order

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#233]
If I have a Markdown file like this:

```
# Some images

![1](1.png)![2](2.png)![3](3.png)![4](4.png)
```

The VSCodium Markdown preview looks like this:

![image](https://github.com/chirun-ncl/chirun/assets/5698564/a54dfc6f-7a3a-4643-b5df-37e3e5b2df3f)

The output from chirun looks like this

![image](https://github.com/chirun-ncl/chirun/assets/5698564/4d956096-071e-4131-b3a9-9b7f30ef83f3)

I don't know why there is so much white space, nor why the images are out of sequence. 

The rendered HTML has three of the images places in `<figure>` environments and the other isn't. I don't understand `<figure>` but I guess these might float? But the order in the HTML is 2,1,4,3, which seems strange.

```
    <article class="item-content" id="item-content">
        <section>
<h1 id="some_images">Some images</h1>
<p><img alt="2" src="images/2.png"/></p>
<figure class="figure1" data-title="1"><img alt="1" src="images/1.png"/></figure><p><img alt="4" src="images/4.png"/></p><figure class="figure3" data-title="3"><img alt="3" src="images/3.png"/></figure>
</section>

    </article>
```

I tried both Firefox and Chromium on Ubuntu.

(My workaround for the real version of this was that I edited the row of images into a single image.)

**Comment by christianp** [comment]
That's really weird!

I've made a really simple test case at https://lti.chirun.org.uk/media/chirun-packages/output/80e35e42-c541-46bd-8fa7-d5a054ec0820/untitled_chapter/index.html. 

Putting space characters between the images doesn't help, nor does a single newline. At least it looks correct when each image is in its own paragraph.
