### ISSUE TITLE
scalebox is implemented in graphics, but not graphicx

### ISSUE THREAD

**Issue by Lycanic** [chirun-ncl/chirun#266]
LaTeX only requires the package graphicx to use scalebox, but within chirun/plastex we require the package graphics instead.

**Comment by christianp** [comment]
@Lycanic can you fix this? I think that you just need to copy the template from [`graphicx.jinja2s`](https://github.com/chirun-ncl/chirun/blob/3c1096a04802cab7770d6ded301b2108cdf60988/chirun/plasTeXRenderer/Renderers/ChirunRenderer/graphicx.jinja2s#L17) to `graphics.jinja2s`.

**Comment by Lycanic** [comment]
The fix is to include the "class scalebox" definition from graphics.py in graphicx.py. I believe we need to do this in https://github.com/christianp/plastex/tree/chirun-running-fixes ?

It looks like currently only some of the graphics classes are brought into graphicx, but I get the impression it should be all of them. I could include rotatebox/reflectbox as well.

I'm not sure whether there is a reason that they define scalebox in graphics.py and not in graphicx.py, but it is definitely the case that graphicx is sufficient to use scalebox in LaTeX!

**Comment by Lycanic** [comment]
Never mind, you're right! I need to understand how jinja2s works...
