### ISSUE TITLE
What types are there? (Create proper documentation)

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#43]
In `config.yml`, I am aware of:

- `introduction`: puts `leading_text` into the top of the page under the title and renders `source` as HTML in the bottom of the page;
- `part`: makes a box/subpage to collect some other content together;
- `chapter`: page of content, notes;
- `slides`: presentation slides;
- `url`: links to a URL.

Are there other valid values for a `type` I am unaware of? What do they do? Are any of my descriptions above incomplete/inaccurate?

**Comment by georgestagg** [comment]
Apologies for the lack of documentation, at some point when things are a little more stable I will write everything up. For the moment, there's a list of types in item.py:

```
    'introduction': Introduction,
    'part': Part,
    'document': Document,
    'chapter': Chapter,
    'standalone': Standalone,
    'url': Url,
    'html': Html,
    'slides': Slides,
    'recap': Recap,
    'exam': Exam,
```

Your descriptions of the types sound right and the others are,

 * `document`: Takes advantage of plastex's ability to split documents, so as to turn a LaTeX source document with multiple chapters into a `part` object, with each chapter in the document output as a separate `chapter` object. This item is fairly new, so I would expect bugs.

 * `standalone`: Takes a source object and creates an output with no real structure. That is, the website will consist of that single document output as `index.html`. This type should be used alone without any parts, chapters or introduction types present.

 * `html`: Include a html source object in the output. Largely untested, but should work.

The remaining items are only useful for our own institution and are deprecated. They will disappear from the code in time,

 * `recap`: Originally designed for including a video on our institution's video management service. This item is no longer required to include videos and only in place for backwards compatibility.

 * `exam`: Include a LaTeX exam typeset in our school's exam template. Again, no longer required but kept for backwards compatibility.

**Comment by christianp** [comment]
I'm reopening this to remind you to put this in some proper documentation :wink:

**Comment by georgestagg** [comment]
Item documentation is now at https://chirun.readthedocs.io/en/latest/content_items.html
