### ISSUE TITLE
I'm doing "pip install -r requirements.txt" but got this issue

### ISSUE THREAD

**Issue by dgarc453** [chirun-ncl/chirun#80]
ERROR: Cannot install -r requirements.txt (line 1) and colorama==0.3.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested colorama==0.3.9
    awsebcli 3.12.1 depends on colorama==0.3.7

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

This is the requirements.txt file:

awsebcli==3.12.1
Babel==2.5.3
blessed==1.14.2
blinker==1.4
botocore==1.8.36
cement==2.8.2
click==6.7
colorama==0.3.9
defusedxml==0.5.0
docker-py==1.7.2
dockerpty==0.4.1
docopt==0.6.2
docutils==0.14
Flask==0.12.2
Flask-AppBuilder==1.9.6
Flask-Babel==0.11.1
Flask-Login==0.2.11
Flask-Mail==0.9.1
flask-mongoengine==0.9.5
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.1
Flask-WTF==0.14.2
itsdangerous==0.24
Jinja2==2.10

**Comment by georgestagg** [comment]
I'm not sure that's our `requirements.txt`, ours looks like this:
```
appdirs>=1.4.3
arrow>=0.10.0
beautifulsoup4>=4.8.0
bs4>=0.0.1
funcsigs>=1.0.2
Jinja2>=2.9.6
jinja2-time>=0.2.0
Markdown==3.1.1
MarkupSafe==1.1.1
markdown-figure==0.0.1
mdx-outline==1.3.0
mock>=2.0.0
olefile>=0.44
packaging>=16.8
pbr>=2.0.0
Pillow>=4.2.1
plasTeX==2.1
py>=1.4.33
Pygments>=2.4.2
pymdown-extensions==6.0
pyoembed>=0.1.2
pyparsing>=2.2.0
PyPDF2>=1.26.0
pyppeteer>=0.0.25
pytest>=3.0.7
python-dateutil>=2.6.0
PyYAML>=5.3
six>=1.10.0
typing-extensions>=3.7.4.3
Unidecode>=1.0.22
```

Can you check for me that you're running the command while inside the `makecourse` directory?
