### ISSUE TITLE
Markdown local file links in PDF output

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#82]
I have been including static files by creating a Markdown file that links to the file in /static/files. (I would prefer for the most part to use `url` in `config.yml` to link to the file directly, but this causes broken links in some places, see #54.) 

I just noticed a problem where the link in the PDF version of this is to the local file on my computer. 

So if I create a Markdown file like this:

```
# Test file

[Download the test file](/static/files/test.docx)
```

It creates HTML like this:

```
<div id="content" class="col-md-9"> 
            
            <section class="section1"><h1>Test file</h1>
<p><a href="../../static/files/test.docx">Download the test file</a></p>
</section>
            </div>
```

Which works fine. However, it also creates a PDF version of the file and in this the text "Download the test file" is linked to `file:///home/.../build/default/static/files/test.docx` and does not work on the web server. (The `...` is the path to where I have makecourse and my course files locally.)

**Comment by christianp** [comment]
Well, I've just tried this and in the PDF version the links aren't clickable at all, so this is sort of resolved?

There should be a separate issue about having clickable links in PDF versions of markdown content, though.

I note that when I use firefox to save the HTML version as a PDF, the file has clickable links, correctly relative to the URL the page was loaded from. The version chirun makes, using chromium, seems to just be a raster of the page, and text isn't even selectable.

**Comment by prowlett** [comment]
I agree that the links in Markdown aren't clickable, and about the need for another issue.

**Comment by christianp** [comment]
Reopening this because the links are still wrong, and include the local server's address. Chirun currently uses a local HTTP server to serve files before pyppeteer converts them to PDF, so that browser security restrictions are avoided.
This means that all links in the produced PDFs will be relative to something like `http://localhost:40392`, where the port number is 

We might have to post-process URIs in PDFs produced from markdown.

I think the following will print all link URIs in a given PDF file:

```python
from pypdf import PdfReader

reader = PdfReader('doc.pdf')

for page in reader.pages:
    for annot in p.get('/Annots'):
        a = annot.get('/A')
        if not a:
            continue
        uri = a.get('/URI')
        if uri is None:
            continue
        print(uri)
```
