### ISSUE TITLE
generate_chapter_subitems forces plastex to run every time

### ISSUE THREAD

**Issue by christianp** [chirun-ncl/chirun#97]
There's some logic that tries to avoid rendering items that haven't changed since the last build. When a document is split into separate chapters, plastex has to run over the tex every build in order to identify the sections. Is there a way of caching the induced structure, so that plastex doesn't have to run if the source hasn't changed?

**Comment by georgestagg** [comment]
Looks like I set up the document structure to be cached a while back (5a0b577e5a5b3fb27d4c01023a0e6545f774cc05) as `.dst` files. Probably I just forgot to close the issue.
